# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17acaaac3d59a717ec2c44c26b09ba674e8c9605d8f89d5863b30dd86839dbac63aef7c98529fa14872971faad50d3ef83add11481f4ca2b482cc95e8cd03db5

test:
  secret_key_base: c82fc2db2179fb251f6d6007fbf545f93b7ac17846de7c938ae1dc932858d5d1ca0c5057d519e33f93a37c8d97590e37a3ffd747316c84dd014dc2d62d3793de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
